version: '3.8'

services:
  # Hộp 1: Database (Giữ nguyên không đổi)
  db:
    image: mysql:8.0
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hoc_devops_db
      MYSQL_USER: yen_user
      MYSQL_PASSWORD: yenpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Hộp 2A: Java Sinh đôi số 1
  backend1:
    image: ghcr.io/thailanhat7-del/hoc-java-devops:latest
    container_name: java_app_1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hoc_devops_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=yen_user
      - SPRING_DATASOURCE_PASSWORD=yenpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update 
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # Hộp 2B: Java Sinh đôi số 2 (Y hệt số 1)
  backend2:
    image: ghcr.io/thailanhat7-del/hoc-java-devops:latest
    container_name: java_app_2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hoc_devops_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=yen_user
      - SPRING_DATASOURCE_PASSWORD=yenpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update 
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # Hộp 3: Lễ tân Nginx (Cập nhật lại mục depends_on)
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend1
      - backend2
    restart: always

volumes:
  db_data:
  # Hộp 2: Java App (Đã đóng kín cửa, không cho khách vào thẳng nữa)
  backend:
    image: ghcr.io/thailanhat7-del/hoc-java-devops:latest
    container_name: java_app
    # ĐÃ XÓA dòng ports "8080:8080" ở đây!
    environment:
      # Báo cho Java biết đường dẫn đến Database. 'db' chính là tên của hộp 1.
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hoc_devops_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # Cấp tài khoản cho Java chui vào
      - SPRING_DATASOURCE_USERNAME=yen_user
      - SPRING_DATASOURCE_PASSWORD=yenpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update 
    # SỬA LẠI: Luật khởi động mới
    depends_on:
      db:
        condition: service_healthy # Đợi hộp db nhận mộc xanh 'healthy' mới được chạy
    restart: always

  # Hộp 3: Lễ tân Nginx (MỚI THÊM)
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html  # THÊM DÒNG NÀY VÀO ĐÂY
    depends_on:
      - backend
    restart: always

volumes:
  db_data: