# THÊM MỚI 1: Tạo một định dạng sổ tay riêng tên là 'chiabai_log'
log_format chiabai_log 'Khách gọi: $request ===> Nginx giao cho anh Java ở phòng: $upstream_addr | Kết quả: $status';

upstream my_java_cluster {
    server backend1:8080;
    server backend2:8080;
}

server {
    listen 80;
    server_name localhost;

    # THÊM MỚI 2: Ép Nginx dùng cuốn sổ tay 'chiabai_log' vừa tạo
    access_log /var/log/nginx/access.log chiabai_log;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://my_java_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}