server {
    # Nginx ngồi ở cửa chính (cổng mặc định của web)
    listen 80;
    
    # Tên miền (hiện tại mình chạy local thì để localhost)
    server_name localhost;

    # Khi có khách truy cập vào bất cứ đường dẫn nào (/)
    location / {
        # Đưa yêu cầu cho nhân viên java_app ở phòng 8080 (gọi đúng tên container)
        proxy_pass http://java_app:8080;
        
        # Giữ lại thông tin của khách hàng để Java biết ai đang gọi
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}